#' Create Treasure Data client
#'
#'
#'@param api_key API key for Treasure Data. You can get this from "API Keys" on https://console.treasuredata.com/users/current
#'@param database Database on Treasure Data to connect.
#'@export
td <- function(api_key, database=NULL)
{
  structure(list(key=api_key, db=database), class="td")
}

#'@export
is.td <- function(x){inherits(x, "td")}

stop_when_not_td <- function(client)
{
  if(!is.td(client)){
    stop("Error: client is not td object")
  }
}

select_db <- function(db1, db2)
{
  ifelse(is.null(db2), db1, db2)
}

stop_when_not_specify_db <- function(db1, db2)
{
  if(is.null(db1) && is.null(db2)){
    stop("You have to specify database as argument or client object(db field)")
  }
}


#' Return a list of your jobs.
#'
#'@param client Treasure Data client generated by td function.
#'
#'data.frame containing the number of jobs, to, from, and jobs an array of the jobs.
#'@export
list_job <- function(client)
{
  stop_when_not_td(client)

  url <- paste0(url_api, "job/list")
  response <- get(client$key, url)
  jsonlite::fromJSON(content(response, "text"))$jobs
}

#'@export
list_table <- function(client, database=NULL)
{
  stop_when_not_td(client)
  stop_when_not_specify_db(client$db, database)

  db <- select_db(client$db, database)
  url <- paste0(url_api, "table/list/", db)
  response <- get(client$key, url)
  jsonlite::fromJSON(content(response, "text"))$tables
}

table_swap <- function(api_key, database, table1, table2)
{

}

#' @export
issue_job <- function(client, query, database=NULL, type="presto", priority=0)
{
  stop_when_not_td(client)
  stop_when_not_specify_db(client$db, database)

  db <- select_db(client$db, database)
  url <- paste0(url_api, sprintf("job/issue/%s/%s", type, db))
  response <- post(client$key, url, list(query=query, priority=priority))
  df <- as.data.frame(jsonlite::fromJSON(content(response, "text")))
  td_job(client, df$job_id, db)
}
